<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Locales;

/**
 * Localized display names for OrganizationCache.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class OrganizationCacheLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => '組織キャッシュ',
        'en' => 'Organization Cache',
        'vi' => 'Cache Tổ chức',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_org_id' => [
            'ja' => 'Console Organization ID',
            'en' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'name' => [
            'ja' => '組織名',
            'en' => 'Organization Name',
            'vi' => 'Tên tổ chức',
        ],
        'code' => [
            'ja' => '組織コード',
            'en' => 'Organization Code',
            'vi' => 'Mã tổ chức',
        ],
        'is_active' => [
            'ja' => '有効',
            'en' => 'Active',
            'vi' => 'Hoạt động',
        ],
    ];
}
