<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Locales;

/**
 * Localized display names for UserCache.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class UserCacheLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => 'ユーザーキャッシュ',
        'en' => 'User Cache',
        'vi' => 'Cache Người dùng',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'name' => [
            'ja' => '名前',
            'en' => 'Name',
            'vi' => 'Tên',
        ],
        'email' => [
            'ja' => 'メールアドレス',
            'en' => 'Email',
            'vi' => 'Email',
        ],
        'console_user_id' => [
            'ja' => 'Console User ID',
            'en' => 'Console User ID',
            'vi' => 'Console User ID',
        ],
        'console_access_token' => [
            'ja' => 'Console Access Token',
            'en' => 'Console Access Token',
            'vi' => 'Console Access Token',
        ],
        'console_refresh_token' => [
            'ja' => 'Console Refresh Token',
            'en' => 'Console Refresh Token',
            'vi' => 'Console Refresh Token',
        ],
        'console_token_expires_at' => [
            'ja' => 'Console Token有効期限',
            'en' => 'Console Token Expiry',
            'vi' => 'Hạn Token Console',
        ],
        'roles' => [
            'ja' => 'ロール',
            'en' => 'Roles',
            'vi' => 'Vai trò',
        ],
    ];
}
