<?php

namespace Omnify\SsoClient\Models\OmnifyBase\Locales;

/**
 * Localized display names for Branch.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */
class BranchLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'ja' => '支店',
        'en' => 'Branch',
        'vi' => 'Chi nhánh',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_branch_id' => [
            'ja' => 'Console Branch ID',
            'en' => 'Console Branch ID',
            'vi' => 'Console Branch ID',
        ],
        'console_org_id' => [
            'ja' => 'Console Organization ID',
            'en' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'code' => [
            'ja' => '支店コード',
            'en' => 'Branch Code',
            'vi' => 'Mã chi nhánh',
        ],
        'name' => [
            'ja' => '支店名',
            'en' => 'Branch Name',
            'vi' => 'Tên chi nhánh',
        ],
    ];
}
