<?php

namespace Omnify\SsoClient\Models\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Omnify\SsoClient\Models\OmnifyBase\Locales\UserCacheLocales;
use Omnify\SsoClient\Models\OmnifyBase\Traits\HasLocalizedDisplayName;
use Omnify\SsoClient\Models\Role;

/**
 * UserCacheBaseModel
 *
 * @property string $name
 * @property string $email
 * @property mixed $console_user_id
 * @property string|null $console_access_token
 * @property string|null $console_refresh_token
 * @property \Carbon\Carbon|null $console_token_expires_at
 * @property \Illuminate\Database\Eloquent\Collection<Role> $roles
 */
class UserCacheBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;

    /**
     * The table associated with the model.
     */
    protected $table = 'user_caches';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The "type" of the primary key ID.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = UserCacheLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = UserCacheLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'console_user_id',
        'console_access_token',
        'console_refresh_token',
        'console_token_expires_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [

    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [

    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'console_token_expires_at' => 'datetime',
        ];
    }

    /**
     * The roles that belong to this model.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'role_user_cache')
            ->withPivot('console_org_id', 'console_branch_id')
            ->withTimestamps();
    }
}
