<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify from schema: Branch
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

namespace App\Http\Requests\OmnifyBase;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

abstract class BranchUpdateRequestBase extends FormRequest
{
    /**
     * Validation rules generated from Omnify schema.
     * All fields use 'sometimes' for partial updates.
     *
     * @return array<string, array<int, mixed>>
     */
    protected function schemaRules(): array
    {
        return [
            'console_branch_id' => ['sometimes', Rule::unique('branches')->ignore($this->route('branch'))],
            'console_org_id' => ['sometimes'],
            'code' => ['sometimes', 'string', 'max:20'],
            'name' => ['sometimes', 'string', 'max:100'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        return [
            'console_branch_id' => 'Console Branch ID',
            'console_org_id' => 'Console Organization ID',
            'code' => 'Branch Code',
            'name' => 'Branch Name',
        ];
    }
}
