<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify from schema: OrganizationCache
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

namespace App\Http\Requests\OmnifyBase;

use Illuminate\Foundation\Http\FormRequest;

abstract class OrganizationCacheStoreRequestBase extends FormRequest
{
    /**
     * Validation rules generated from Omnify schema.
     *
     * Generated fields: console_org_id, name, code, is_active
     *
     * @return array<string, array<int, mixed>>
     */
    protected function schemaRules(): array
    {
        return [
            'console_org_id' => ['required', 'unique:organization_caches'],
            'name' => ['required', 'string', 'max:100'],
            'code' => ['required', 'string', 'max:20'],
            'is_active' => ['required', 'boolean'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        return [
            'console_org_id' => 'Console Organization ID',
            'name' => 'Organization Name',
            'code' => 'Organization Code',
            'is_active' => 'Active',
        ];
    }
}
