<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('branches', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('console_branch_id')->unique()->comment('Console Branch ID');
            $table->uuid('console_org_id')->comment('Console Organization ID');
            $table->string('code', 20)->comment('Branch Code');
            $table->string('name', 100)->comment('Branch Name');
            $table->boolean('is_headquarters')->default(false)->comment('Is Headquarters');
            $table->boolean('is_active')->default(true)->comment('Active');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->index('console_org_id');
            $table->unique(['console_org_id', 'code']);
            $table->index(['console_org_id', 'is_active']);
            $table->index(['console_org_id', 'is_headquarters']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('branches');
    }
};
