<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 *
 * @generated by @famgia/omnify-laravel
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('user_caches', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('name')->comment('Name');
            $table->string('email')->comment('Email');
            $table->uuid('console_user_id')->nullable()->comment('Console User ID');
            $table->uuid('console_org_id')->nullable()->comment('Organization ID');
            $table->text('console_access_token')->nullable()->comment('Console Access Token');
            $table->text('console_refresh_token')->nullable()->comment('Console Refresh Token');
            $table->timestamp('console_token_expires_at')->nullable()->comment('Console Token Expiry');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index('console_org_id');
            $table->unique(['email', 'console_org_id']);
            $table->unique(['console_user_id', 'console_org_id']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('user_caches');
    }
};
