<?php

namespace Omnify\SsoClient\Providers;

use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\ServiceProvider;

/**
 * SsoClient Service Provider
 *
 * This provider is auto-generated by Omnify.
 * Register it in composer.json extra.laravel.providers for auto-discovery.
 */
class SsoClientServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        // Load migrations from package
        $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');

        // Enforce morph map for this package's models
        Relation::enforceMorphMap([
            'Branch' => \Omnify\SsoClient\Models\BranchCache::class,
            'BranchCache' => \Omnify\SsoClient\Models\BranchCache::class,
            'Permission' => \Omnify\SsoClient\Models\Permission::class,
            'Role' => \Omnify\SsoClient\Models\Role::class,
            'RolePermission' => \Omnify\SsoClient\Models\RolePermission::class,
            'Team' => \Omnify\SsoClient\Models\TeamCache::class,
            'TeamCache' => \Omnify\SsoClient\Models\TeamCache::class,
            'TeamPermission' => \Omnify\SsoClient\Models\TeamPermission::class,
            'User' => \Omnify\SsoClient\Models\UserCache::class,
            'UserCache' => \Omnify\SsoClient\Models\UserCache::class,
            'OrganizationCache' => \Omnify\SsoClient\Models\OrganizationCache::class,
        ]);

        // Backward compatibility aliases (only if classes don't exist)
        if (! class_exists(\Omnify\SsoClient\Models\Branch::class)) {
            class_alias(\Omnify\SsoClient\Models\BranchCache::class, \Omnify\SsoClient\Models\Branch::class);
        }
        if (! class_exists(\Omnify\SsoClient\Models\User::class)) {
            class_alias(\Omnify\SsoClient\Models\UserCache::class, \Omnify\SsoClient\Models\User::class);
        }
        if (! class_exists(\Omnify\SsoClient\Models\Team::class)) {
            class_alias(\Omnify\SsoClient\Models\TeamCache::class, \Omnify\SsoClient\Models\Team::class);
        }
    }
}
